spring:
  application:
    name: torrent-download-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          min-partition-count: 1
      bindings:
        download-message:
          group: torrent-download-group
          destination: downloadMessages
          contentType: application/json
          consumer:
            compressionType: gzip
            auto-offset-reset: earliest
        torrent-message:
          destination: torrentMessages
          contentType: application/json
          producer:
            compressionType: gzip
          consumer:
            compressionType: gzip
            auto-offset-reset: earliest
logging:
  level:
    root: info

download:
  num:
    thread: 20
server:
  port: 8767