mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dht?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: dht
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  application:
    name: torrent-download-service
  redis:
    host:
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    password:

logging:
  level:
    root: info

download:
  num:
    thread: 50
server:
  port: 8767