server:
  port: 8766
## netty服务器端口
netty:
  udp:
    port: 6688
  so:
    rcvbuf: 1048576 #1g
    sndbuf: 65536
    send-limit: 4500

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 1
        max-active: 8
        max-wait: -1ms
    password:
  application:
    name: dht-server


logging:
  level:
    root: info