server:
  port: 8766
## netty服务器端口
netty:
  udp:
    port: 6688
  so:
    rcvbuf: 1048576 #1g
    sndbuf: 65536

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dht?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: dht
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: select 1
      max-lifetime: 30000
      connection-init-sql: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    password:
  application:
    name: torrent-download-service




logging:
  level:
    root: info